# Run docker-compose build
# Run docker-compose up
# docker-compose ps - show all containers
# docker exec -it {container_name} bash -- connect to container

# Symfony: http://localhost:82
# Angular: http://localhost:4200
# Phpmyadmin: http://localhost:8080

version: '3.1'
services:
    apache:
        build: .docker/apache
        container_name: api_apache
        ports:
          - 82:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ${SYMFONY_APP}:/home/wwwroot/api
        depends_on:
          - php
        

    mysql:
        image: mysql:5.7
        container_name: api_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        ports:
          - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        

    php:
        build: .docker/php
        container_name: api_php
        volumes:
          - ${SYMFONY_APP}:/home/wwwroot/api
        depends_on:
          - mysql
        

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: api_phpmyadmin
        restart: always
        ports:
            - 8080:80
        links:
            - mysql
        environment:
          PMA_HOST: mysql
          

    nginx:
      container_name: client_nginx
      build: .docker/nginx
      volumes:
        - ${ANGULAR_APP}/dist/client:/usr/share/nginx/html
      ports:
        - "81:80"
        - "443:443"


    node:
        build: .docker/node
        container_name: client_node
        ports:
            - 4200:4200
            - '49153:49153'
        volumes:
            - ${ANGULAR_APP}:/home/node/app/frontend
        tty: true
        command:
            - /bin/sh
            - -c
            - |
                cd /home/node/app/frontend && npm start
        expose:
            - "4200"
