fos_rest:
    param_fetcher_listener: true
    allowed_methods_listener: true
    view:
        view_response_listener: force
        formats:
            json: true
    format_listener:
        rules:
            - { prefer_extension: false, fallback_format: json, priorities: [ json ] }



