app.swagger.areas:
    path: /api/v1/doc/{area}.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /api/v1/doc/{area}
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }

test:
    path:       /api/v1/test
    controller: App\Controller\TestController::apiWorks
    methods:    GET

answer_get:
    path:       /api/v1/answer/{id}
    controller: App\Controller\AnswerController::getAnswer
    methods:    GET

answer_cget:
    path:       /api/v1/answer
    controller: App\Controller\AnswerController::getAnswers
    methods:    GET

answer_post:
    path:       /api/v1/answer
    controller: App\Controller\AnswerController::postAnswer
    methods:    POST

answer_patch:
    path:       /api/v1/answer/{id}
    controller: App\Controller\AnswerController::patchAnswer
    methods:    PATCH

answer_delete:
    path:       /api/v1/answer/{id}
    controller: App\Controller\AnswerController::deleteAnswer
    methods:    DELETE